### PR TITLE
Handle exposing (..) in NoRedundantlyQualifiedType

### PR DESCRIPTION
**Pull request by jfmengels**
Adds support for handling `exposing (..)` in the new `NoRedundantlyQualifiedType` rule.

@lydell if you could review this that would be great!
Checking I haven't missed any tests may be the most important part (but any other comment are welcome too)

### CODE REVIEW

**Comment by lydell** [comment]
This looks great!

I ran it at work, and it found a couple of more things to simplify compared to before this PR, and it caused no compilation errors.

The code and tests look good (I learned a lot from reading it). The only thing I noticed not being tested, is `import ... exposing (..)` from an installed package (dependency). Or did I just miss it?

**Comment by jfmengels** [comment]
Good catch! I've added some tests with dependencies.

**Comment by jfmengels** [comment]
You may notice that in the new test code with dependencies, there is code like `Project.Project` (from `import Review.Project as Project`). Was this purposefully not handled @lydell? If it is, then I think we should document that. If it isn't, then maybe we should add this handling when the type alias is also the same as the type name. What do you think?

**Comment by lydell** [comment]
I’m not sure if I follow. Can you show an example?

I did notice one thing in the new tests, though (but it doesn’t sound like what you are describing?). For `OtherSetTypeAlias`:

```elm
test "should not report an error if an import from a dependency exposes a type alias we want to shorten (exposing all)" <|
            \() ->
                """module A exposing (..)
import Set
import OtherSetTypeAlias exposing (..)
a : Set.Set a
a = Set.empty
"""
```

I guess it _would_ be safe to shorten `Set.Set` here, if the type alias in `OtherSetTypeAlias` is actually an alias for the real `Set`? But for me, it doesn’t matter if we support this or not, it feels like too much of an edge case.

**Comment by jfmengels** [comment]
> I’m not sure if I follow. Can you show an example?

Oh sorry, I meant that in the test file (not in code evaluated in a test), there is an annotation that says `Project.Project`. It's here: https://github.com/jfmengels/elm-review-code-style/pull/13/commits/ffa4bbdd7d9ba34626a4cfd8d3bcd3cb4933b0d9#diff-2ca53b07e3fa575ffd8e854e6fa24ae667db55dd936bb39d0f9e0f3fe1264bb5R596

It's not being shortened because the import is `import Review.Project as Project`. And I was wondering whether we should shorten this one (as long as it doesn't create a compiler error).

> I guess it would be safe to shorten Set.Set here, if the type alias in `OtherSetTypeAlias` is actually an alias for the real Set?

Wouldn't it create a compiler error still? :thinking: 
But I don't think we should anyway. It would be somewhat surprising, and it might mess up someone's refactoring (where they want to switch from `Set` to a custom type in several steps).
I'm not convinced either way, so I'd probably skip this for now, but I'm happy to be convinced otherwise.

**Comment by lydell** [comment]
> It's not being shortened because the import is `import Review.Project as Project`. And I was wondering whether we should shorten this one (as long as it doesn't create a compiler error).

That’s supposed to be shortened, yes. I thought we already did that, and already had a test in my PR? Or is this special because it’s importing something from an installed package?

**Comment by jfmengels** [comment]
> I thought we already did that, and already had a test in my PR?

Maybe I broke that functionality, but I don't think there was such a test. I at least don't see the `as` keyword in any test (and I haven't removed one in this PR).

But good to know. I'll try to re-add it.

EDIT: I've added a test locally, and yes it already works, just not in the situation I've tried. I think it's because it's from an installed package yes. I'll continue working on it.

**Comment by jfmengels** [comment]
Nevermind, I had enabled it in the wrong `ReviewConfig.elm` file (the `example/` one) instead of the project's :facepalm: 

I still added a test for the import alias. I think this is now ready to be merged, and therefore to be published!
Do you see anything I'm missing?

**Comment by lydell** [comment]
Awesome! Then I think this is good to go. I can’t think of anything else! Thank you for finishing the part of the rule that was difficult for me.

**Comment by jfmengels** [comment]
Awesome! Thank you for the help!
I'll publish it now.

**Pull request merged**
